--NAME      OPEN_MODE
--------- --------------------
--CRM       READ WRITE
create tablespace AMAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace ARAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace ARLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace BIAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace BNAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace BPAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace BPLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace CFGAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace CPAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace CRAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace CULARG1 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace CULARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOBFAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOCFAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOCMAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOCMLRG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOCMWRK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOCUAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOCULRG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EODSAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EODSLRG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOECAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOECLRG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOECWRK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOEIAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOEILRG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOEPAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOEWAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOEWLRG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOEWWRK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOIUAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOIULRG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOIUWRK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOLTAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOPPAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOPPLRG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOTPAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace EOTPLRG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace FSAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace FSLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace HRAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace HRLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace INAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace INLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace JUNK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace LCAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace MGAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace OMAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace OMLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace POAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PSDEFAULT datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PSIMAGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PSIMAGE2 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PSIMGR datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PSINDEX datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PSTEMP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PSWORK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTAMSG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTAPPE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTAUDIT datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTCMSTAR datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTLOCK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTPRC datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTPRJWK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTRPTS datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTTBL datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTTLRG datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTTREE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PTWORK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace PWAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RAAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RABINDEX datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RABLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RALARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RBAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RBDLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RBIMAGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RBLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RBROW datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RBTASK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RBTEMP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RCAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RCLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RDWORK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace REAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RELARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RFAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RFLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RGAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RGLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RIAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RILARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace ROAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace ROLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RQAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RQLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RSAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RSFAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RSFLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RSLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RSPAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RSPLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RTAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RYAPP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RYAPP1 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RYLARG1 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RYLARG2 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RYLARG3 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RYLARGE datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RYWORK datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RYWORK1 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RYWORK2 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
create tablespace RYWORK3 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
--create tablespace SYSAUX datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
--create tablespace SYSTEM datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
--create tablespace TEMP datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
--create tablespace UNDOTBS1 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
--create tablespace UNDOTBS2 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
--create tablespace UNDOTBS3 datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;
--create tablespace USERS datafile '+DATA' size 50M autoextend on maxsize UNLIMITED EXTENT MANAGEMENT LOCAL;

-- 123 rows selected.
-- Two encrypted tablespaces
create tablespace HRCC_SYSADM_DATA_TDE datafile '+DATA'
size 50M autoextend on next 10M encryption using 'AES256' default storage (encrypt);

create tablespace HRCC_SYSADM_INDEX_TDE datafile '+DATA'
size 50M autoextend on next 10M encryption using 'AES256' default storage (encrypt);


